name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    #runs-on: ubuntu-latest
    #runs-on: debian:bullseye-slim
    runs-on: [self-hosted, linux]
    container:
      # Runner docker image
      image: ubuntu:22.04
#    defaults:
#      run:
#        working-directory: ./scripts
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: install needed packages
      run: apt-get update && apt install -y build-essential cmake doxygen graphviz clang clang-format git
#    - name: Checkout submodules due to github thing
#      run: git submodule update --init --recursive
    - name: install dependencies
      working-directory: ./scripts
      run: ./install-catch2.sh
    - name: build
      working-directory: ./scripts
      run: build-all.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: test_suite
        path: build/test/test_suite
        retention-days: 1 optional
